import { IProjectItem } from '../types/projects'

export const PROJECTS: IProjectItem[] = [
  {
    id: 14,
    title: 'Papua University Academic Information System',
    slug: 'papua-university-academic-information-system',
    description: "Papua University Academic Information System Dashboard.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1722563818/Screenshot_157_oocxoa.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'TailwindCSS', 'PHP', 'Next.js', 'TypeScript', 'MySQL'],
    is_show: true,
    is_featured: false,
  },
  {
    id: 13,
    title: 'Kimroom Store Management System',
    slug: 'kimroom-store-management-system',
    description: "Kimroom Store Management System, Accounting System, Inventory Management System, and Point of Sales.",
    image: 'https://res.cloudinary.com/dnbel4bdy/image/upload/v1717116418/projects/y9vqsh5ce4neao1iopio.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'Bootstrap', 'PHP', 'React.js', 'TypeScript', 'MySQL'],
    is_show: true,
    is_featured: false,
    is_other: true
  },
  {
    id: 12,
    title: 'Store Management System',
    slug: 'shop-management-system',
    description: "Store Management System, Accounting System, and Inventory Management System",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1722562669/Screenshot_154_avndps.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'Bootstrap', 'PHP', 'JavaScript', 'MySQL'],
    is_show: true,
    is_featured: false,
    is_other: true
  },
  {
    id: 11,
    title: 'Hekku Top Up',
    slug: 'hekku-top-up',
    description: "Top Up Game built with Next.Js and Tailwind CSS.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1708395855/projects/rf9xxuzq2xy6w3r03bku.png',
    link_demo: null,
    link_github: null,
    stacks: ['Next.js', 'TailwindCSS', 'TypeScript', 'Laravel', 'PHP', 'MySQL', 'Firebase'],
    is_show: true,
    is_featured: true,
    is_own: true
  },
  {
    id: 10,
    title: 'Kris Store',
    slug: 'kris-store',
    description: "eCommerce Template built with Next.Js and Tailwind CSS based on Figma Community Design, fully responsive ( https://www.figma.com/file/yuxyGBsdwKSZ9jzYkNhQ9I/Figma-ecommerce-UI-Kit-(web-%26-mobile)-(Community) ).",
    image: 'https://res.cloudinary.com/dnbel4bdy/image/upload/v1705013781/kris-store/mxa4ybv40sui5swzayto.png',
    link_demo: 'https://kris-store.vercel.app/',
    link_github: 'https://github.com/kriskurniawan/kris-store',
    stacks: ['Next.js', 'TailwindCSS', 'TypeScript'],
    is_show: true,
    is_featured: false,
    is_own: true
  },
  {
    id: 9,
    title: 'KrisCommerce Template',
    slug: 'kriscommerce-template',
    description: "eCommerce Template built with Next.Js and Tailwind CSS based on Figma Community Design ( Electon - https://www.figma.com/file/BdcRd5HaNmHsKmronOVfyX/e-commerce-(Community) ).",
    image: 'https://res.cloudinary.com/dnbel4bdy/image/upload/v1705013359/kris-store/vpztekyej2rf4fdio1m4.png',
    link_demo: 'https://kriscommerce-template.vercel.app/',
    link_github: 'https://github.com/kriskurniawan/kriscommerce-template',
    stacks: ['Next.js', 'TailwindCSS', 'TypeScript'],
    is_show: true,
    is_featured: false,
    is_own: true
  },
  {
    id: 8,
    title: 'Nanojastip',
    slug: 'nanojastip',
    description: "Parcel Delivery Service in the city of Manokwari.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1722563609/Screenshot_155_vwjqtc.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false
  },
  {
    id: 7,
    title: 'Simama Wondama',
    slug: 'simama-wondama',
    description: "The Civil Servant Management Information System of Wondama.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1700894403/projects/hbcvpzcopbd3kcfsh01x.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false
  },
  {
    id: 6,
    title: 'BPBD Sorsel',
    slug: 'bpbd-sorsel',
    description: "Natural Disaster Information System of the South Sorong District Disaster Management Agency (BPBD).",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1700894085/projects/i578wlaiqxohmmwkrz2s.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false
  },
  {
    id: 5,
    title: 'Simasku Manokwari',
    slug: 'simasku-manokwari',
    description: "The Human Resources Information System of Manokwari Regency.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1700893686/projects/ssqkj5aleq4eq4lz7zmz.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false
  },
  {
    id: 4,
    title: 'Yayasan Anak Yatim',
    slug: 'yayasan-anak-yatim',
    description: "The Information Website of Ikhsan Al Mauun Orphanage Foundation in the City of Manokwari.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1700892568/projects/anbhgdczyszgaj3sk2jy.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false
  },
  {
    id: 3,
    title: 'SISBPAK',
    slug: 'sisbpak',
    description: "The Information System for the Academic Planning and Student Affairs Office at Papua University.",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1700881080/projects/y6jlsaeppbkbqxi1isdd.png',
    link_demo: null,
    link_github: null,
    stacks: ['Laravel', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false
  },
  {
    id: 2,
    title: 'SBPSIA & IJMSIA',
    slug: 'sbpsia-ijmsia',
    description: "Pharmacy Management System PT. Sinar Bintang Papua & PT. Irman Jaya Martabe",
    image: 'https://res.cloudinary.com/dnbel4bdy/image/upload/v1717116418/projects/slc4cqemisxaf0xrxbwe.png',
    link_demo: null,
    link_github: null,
    stacks: ['CodeIgniter', 'PHP', 'JavaScript', 'Bootstrap', 'MySQL'],
    is_show: true,
    is_featured: false,
    is_other: true
  },
  {
    id: 1,
    title: 'Kriskurniawan.my.id',
    slug: 'kriskurniawan-my-id',
    description: "Personal Portfolio Website",
    image: 'https://res.cloudinary.com/dgaf5rmnv/image/upload/v1702940643/projects/pux2za5mfm18sbs3snw0.png',
    link_demo: 'https://kriskurniawan.my.id',
    link_github: 'https://github.com/kriskurniawan/kriskurniawan.my.id',
    stacks: ['Next.js', 'TypeScript', 'TailwindCSS', 'Prisma'],
    is_show: true,
    is_featured: true,
    is_other: false
  }
]
